name: Linux Tag Checker

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

env:
  TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

jobs:
  goCheck:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check now
      run: |
        git clone https://XSans0:$GIT_TOKEN@github.com/XSans0/linux-tag-checker.git
        cd linux-tag-checker
        bash check.sh